### ISSUE TITLE
Blank code viewer on opening empty directories

### ISSUE THREAD

**Issue by ZahraTee** [nrc/cargo-src#191]
If we're planning to let the user continue to navigate through the code viewer itself, and thus open empty directories, we should add some sort of message to let them know there's actually nothing in there. But if we're restricting navigation to the filetree this won't be an issue. :)

![screen shot 2018-04-02 at 18 53 10](https://user-images.githubusercontent.com/5565340/38207903-31fe3cc6-36a7-11e8-9d37-c1eaa7567447.png)

**Comment by nrc** [comment]
I wasn't planning to limit navigation to the tree view, though it does feel a bit weird having two ways to navigate
