### ISSUE TITLE
Windows: Will not install under Powershell

### ISSUE THREAD

**Issue by kjeremy** [nrc/cargo-src#216]
Running `cargo install cargo-src` on nightly ends up with a bunch of errors:

>    Compiling miow v0.2.1
>    Compiling thread_local v0.2.7
>    Compiling bytes v0.4.6
>    Compiling regex v0.1.80
>    Compiling rls-analysis v0.12.0
>    Compiling tokio-io v0.1.6
>    Compiling mio v0.6.14
>    Compiling serde_derive v1.0.39
>    Compiling tokio-reactor v0.1.1
>    Compiling tokio-tcp v0.1.0
>    Compiling tokio-udp v0.1.0
>    Compiling env_logger v0.3.5
>    Compiling tokio v0.1.5
>    Compiling tokio-core v0.1.17
>    Compiling tokio-proto v0.1.1
>    Compiling hyper v0.11.25
>    Compiling cargo_metadata v0.5.4
> error: unknown character escape: U
>  --> C:\Users\jkolb\AppData\Local\Temp\cargo-installoWD3cv\release\build\cargo-src-49fef487575c9978\out/lookup_static.rs
> :5:42
>   |
> 5 | ".eslintignore" => Ok(include_bytes!("C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-src-0.1.0
> \static\.eslintignore")),
>   |                                          ^
> 
> error: unknown character escape: j
>  --> C:\Users\jkolb\AppData\Local\Temp\cargo-installoWD3cv\release\build\cargo-src-49fef487575c9978\out/lookup_static.rs
> :5:48
>   |
> 5 | ".eslintignore" => Ok(include_bytes!("C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-src-0.1.0
> \static\.eslintignore")),
>   |                                                ^
> 
> error: unknown character escape: .
>  --> C:\Users\jkolb\AppData\Local\Temp\cargo-installoWD3cv\release\build\cargo-src-49fef487575c9978\out/lookup_static.rs
> :5:54
>   |
> 5 | ".eslintignore" => Ok(include_bytes!("C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-src-0.1.0
> \static\.eslintignore")),
>   |                                                      ^
> 
> error: unknown character escape: s
>  --> C:\Users\jkolb\AppData\Local\Temp\cargo-installoWD3cv\release\build\cargo-src-49fef487575c9978\out/lookup_static.rs
> :5:70
>   |
> 5 | ".eslintignore" => Ok(include_bytes!("C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-src-0.1.0
> \static\.eslintignore")),
>   |                                                                      ^

**Comment by nrc** [comment]
dup of #210
