### ISSUE TITLE
Render markdown docs

### ISSUE THREAD

**Issue by nrc** [nrc/cargo-src#229]
There are a lot of markdown files in Rust projects, and they can be a pain to read in source view, rendering them would be really nice.

We'd want to be able to view both rendered and source, probably rendered by default. Having a markdown renderer might be cool for docs too. I'm not sure whether we'd be better to render on the server or client side. The client might be easier, but the server could cache the rendered version easily in the file cache.

**Comment by Vurich** [comment]
Closed by #241
