### ISSUE TITLE
Render markdown docs

### ISSUE THREAD

**Issue by Vurich** [nrc/cargo-src#246]
So I think it'd be cool to show the documentation rendered by default with the option to show it as it appears in the source code. Combined with #245 you could make reading a source file with `cargo src` as nice as reading `rustdoc` output, with the added ability to seamlessly show and navigate the source code.

**Comment by nrc** [comment]
I think this would be nice, we'd just have to be careful to keep line numbers accurate.

**Comment by Vurich** [comment]
We can just store the line number on the line object

**Comment by matthiasbeyer** [comment]
Duplicate of #229 ?
